# Generated by Django 5.1.2 on 2024-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del perrito', max_length=100)),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Macho'), (2, 'Hembra')], default='1', help_text='1-Macho, 2-Hembra')),
                ('edad', models.DecimalField(decimal_places=1, help_text='Ingresar la edad en años y meses', max_digits=3)),
                ('historia', models.TextField(help_text='Ingrese una breve descripcion del perrito y su historia', max_length=1000)),
                ('fotos', models.ImageField(upload_to='perritos_app/images')),
                ('talla', models.CharField(choices=[('p', 'pequeño'), ('m', 'mediano'), ('g', 'grande')], default='m', help_text='Ingresar la talla del perro', max_length=1)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
            },
        ),
    ]
