# Generated by Django 5.1.2 on 2024-10-29 15:29

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del perrito', max_length=100)),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Macho'), (2, 'Hembra')], default='1', help_text='1-Macho, 2-Hembra')),
                ('edad', models.DecimalField(decimal_places=0, help_text='Ingresar la edad en años', max_digits=2)),
                ('historia', models.TextField(help_text='Ingrese una breve descripcion del perrito y su historia', max_length=1000)),
                ('talla', models.CharField(choices=[('p', 'Pequeño'), ('m', 'Mediano'), ('g', 'Grande')], default='m', help_text='Ingresar la talla del perro', max_length=1)),
                ('status', models.BooleanField(default=1, help_text='Habilitar si el perro está disponible para adoptar')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
            },
        ),
        migrations.CreateModel(
            name='PerroFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='perritos_app.perro')),
            ],
        ),
    ]
