# Generated by Django 5.1.2 on 2024-10-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos_app', '0002_alter_perro_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='fotos',
        ),
        migrations.AlterField(
            model_name='perro',
            name='status',
            field=models.BooleanField(default=1, help_text='Habilitar si el perro está disponible para adoptar'),
        ),
        migrations.CreateModel(
            name='PerroFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='perritos_app/images')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='perritos_app.perro')),
            ],
        ),
    ]
