# Generated by Django 5.1.2 on 2024-10-28 14:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos_app', '0004_alter_perro_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrofotos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='perrofotos',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.DecimalField(decimal_places=0, help_text='Ingresar la edad en años', max_digits=2),
        ),
    ]
