# Generated by Django 5.1.2 on 2024-10-29 13:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos_app', '0005_remove_perrofotos_imagen_perrofotos_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrofotos',
            name='image',
        ),
        migrations.AddField(
            model_name='perrofotos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
